linters-settings:
    # https://golangci-lint.run/usage/linters/#gofumpt
    gofumpt:
        lang-version: "1.19"

# https://golangci-lint.run/usage/linters/
linters:
    presets:
        - bugs
        - comment
        - complexity
        - error
        - format
        - import
        - metalinter
        - module
        - performance
        - sql
        - style
        - test
        - unused
    disable:
        - deadcode # deprecated
        - errname
        - exhaustivestruct # deprecated
        - exhaustruct
        - forbidigo
        - golint # deprecated
        - gosec # TODO: Should enable when ready
        - ifshort # deprecated
        - interfacer # deprecated
        - ireturn
        - maligned # deprecated
        - nlreturn
        - nosnakecase # deprecated
        - paralleltest
        - rowserrcheck # deprecated
        - scopelint # deprecated
        - sqlclosecheck # deprecated
        - structcheck # deprecated
        - varcheck # deprecated
        - varnamelen
        - wastedassign # deprecated
        - wsl
