---
name: "ci"

on:
    pull_request:
        branches:
            - "main"
    push:
        branches:
            - "main"

permissions: "read-all"

jobs:
    ci:
        runs-on: "ubuntu-latest"

        steps:
            - uses: "actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c"
            - uses: "pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd"
              with:
                  version: "latest"
            - uses: "actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c"
              with:
                  node-version-file: ".nvmrc"
                  cache: "pnpm"
            - uses: "actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568"
              with:
                  go-version-file: "./go.mod"
            - run: "make install"
            - run: "make build"
            - run: "make lint_pnpm"
            - uses: "golangci/golangci-lint-action@0ad9a0988b3973e851ab0a07adf248ec2e100376"
              with:
                  version: "latest"
            - run: "make test"
